### PR TITLE
Improved discord posting

### PR DESCRIPTION
**Pull request by jondekerh**
updated postToDiscord() to use embeds and give more product information. also added .gitignore file for node_modules

### CODE REVIEW

**Comment by jondekerh** [comment]
Here's an example of what it posts to Discord with these updates:
untitled

**Comment by patron0110** [comment]
im getting this error :

internal/modules/cjs/loader.js:633
    throw new ERR_INVALID_ARG_VALUE('id', id,
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:633:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\User\Downloads\cmder\SupremeRestocks\supreme.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by julianpolyt** [comment]
internal/modules/cjs/loader.js:633
    throw new ERR_INVALID_ARG_VALUE('id', id,
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:633:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\User\Downloads\cmder\SupremeRestocks\supreme.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

im getting this error bro?

**Comment by jondekerh** [comment]
turns out discord-bot-webhook does not support embeds. closing this pull request. will re-open it once ive updated everything using a library which does.

**Pull request closed without merging**
